# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('installed', models.DateField()),
                ('installation_index', models.PositiveIntegerField()),
                ('disposed', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lon', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('PV', 'Photovolta\xefque'), ('WP', 'Parc \xe9olien')], max_length=2)),
                ('installed', models.DateField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexmgr.Meter')),
            ],
        ),
        migrations.CreateModel(
            name='SiteDailyProduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meter_value', models.PositiveIntegerField()),
                ('index', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('M', 'Entr\xe9e manuelle'), ('I', 'Entr\xe9e import\xe9e'), ('C', 'Entr\xe9e calcul\xe9e')], max_length=1)),
                ('production', models.PositiveIntegerField(null=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexmgr.Meter')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexmgr.Site')),
            ],
        ),
    ]
